-- MySQL Script generated by MySQL Workbench
-- 04/02/18 22:18:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cadastro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cadastro` ;

-- -----------------------------------------------------
-- Schema cadastro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadastro` DEFAULT CHARACTER SET utf8 ;
USE `cadastro` ;

-- -----------------------------------------------------
-- Table `cadastro`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadastro`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `cadastro`.`funcionario` (
  `idFuncionario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(256) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cadastro`.`projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadastro`.`projeto` ;

CREATE TABLE IF NOT EXISTS `cadastro`.`projeto` (
  `idprojeto` INT NOT NULL AUTO_INCREMENT,
  `nomeProjeto` VARCHAR(255) NOT NULL,
  `descricaoProjeto` TEXT NOT NULL,
  `dataInicio` DATE NOT NULL,
  `dataFim` DATE NOT NULL,
  `statusProjeto` INT(1) NOT NULL,
  PRIMARY KEY (`idprojeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastro`.`funcionario_projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadastro`.`funcionario_projeto` ;

CREATE TABLE IF NOT EXISTS `cadastro`.`funcionario_projeto` (
  `FKFuncionario` INT(11) NOT NULL,
  `FKProjeto` INT NOT NULL,
  `nomeFase` VARCHAR(255) NOT NULL,
  `dataInicialFase` DATE NOT NULL,
  `dataFinalFase` DATE NOT NULL,
  `statusFase` INT(1) NOT NULL,
  `observacaoFase` TEXT NULL,
  PRIMARY KEY (`FKFuncionario`, `FKProjeto`),
  INDEX `fk_funcionario_has_projeto_projeto1_idx` (`FKProjeto` ASC),
  INDEX `fk_funcionario_has_projeto_funcionario_idx` (`FKFuncionario` ASC),
  CONSTRAINT `fk_funcionario_has_projeto_funcionario`
    FOREIGN KEY (`FKFuncionario`)
    REFERENCES `cadastro`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_has_projeto_projeto1`
    FOREIGN KEY (`FKProjeto`)
    REFERENCES `cadastro`.`projeto` (`idprojeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
